QuotePoc.WebUI/Models/Life.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace QuotePoc.WebUI.Models
{
    public class Life
    {
        [Required]
        [StringLength(5, MinimumLength = 2)]
        public string Title { get; set; }

        [Display(Name = "First Name")]
        [Required]
        [StringLength(10, MinimumLength = 3)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required]
        [StringLength(10, MinimumLength = 3)]
        public string LastName { get; set; }

        [Display(Name = "Date of Birth")]
        [Required]
        public DateTime? DateOfBirth { get; set; }
    }
}

QuotePoc.WebUI/Models/Quote.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace QuotePoc.WebUI.Models
{
    public class Quote : IValidatableObject
    {
        public IEnumerable<Life> Lives { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Lives != null &&
                !Lives.Any(l => l.FirstName.Equals("Tom", StringComparison.OrdinalIgnoreCase)))
                yield return new ValidationResult("At least one person must be named Tom", new[] {"Lives"});
        }
    }
}

QuotePoc.WebUI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace QuotePoc.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

QuotePoc.WebUI/Controllers/QuoteController.cs
using System.Net.Mime;
using System.Web.Mvc;
using QuotePoc.WebUI.Models;

namespace QuotePoc.WebUI.Controllers
{
    public class QuoteController : Controller
    {
        [HttpGet]
        public ActionResult Quote()
        {
            return View(new Quote());
        }

        [HttpPost]
        public ActionResult Quote(Quote quote)
        {
            if (!ModelState.IsValid)
            {
                return View(quote);
            }

            return Json(quote, MediaTypeNames.Text.Plain, JsonRequestBehavior.AllowGet);
        }
    }
}

QuotePoc.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Quote POC";
}

<h2>Quote POC</h2>
<p>
    This POC shows how KnockoutJS, jQuery Templating, System.ComponentModel.DataAnnotations
    and ASP.NET MVC 3 can all work together. The example scenario is a life insurance quote
    screen.
</p>
<p>
    It demonstrates:
</p>
<ul>
    <li>
        Live, client-side bindings
        <ul>
            <li>The <em>Calculate</em> button isn't enabled until at least one <em>Life</em> is added.</li>
            <li>The <em>Age Next</em> field is calculated as soon as the <em>Date of Birth</em> field loses focus.</li>
            <li>Bindings are declarative. This increases the robustness of the code by coding a rule such as '<em>calculate button is enabled if there is one or more lives</em>' instead of having to handle the add life and remove life events separately.</li>
        </ul>
    </li>
    <li>
        Complex validation without cross-tier duplication
        <ul>
            <li>All validation is performed on the server for safety.</li>
            <li><em>Most</em> validation is also performed on the client to reduce the feedback cycle.</li>
            <li>Validation rules are shared between the client and server without having to write custom JavaScript. Keeps validation consistent.</li>
            <li>Invalid fields are styled to highlight them and have validation messages shown next to them.</li>
            <li>Complex, multi-property business rules still supported server side. (Example includes a business rule that at least one person must be named Tom.)</li>
        </ul>
    </li>
    <li>
        Client-side templating
        <ul>
            <li>Excel-like grids without crazy manual JavaScript or server postbacks to rebuild UIs</li>
        </ul>
    </li>
    <li>
        High performance
        <ul>
            <li>HTML is lean, mean and highly cachable with donut-caching</li>
            <li>All JavaScript is in external, cachable files</li>
            <li>JavaScript loads at the end of the page</li>
        </ul>
    </li>
    <li>
        Developer friendliness
        <ul>
            <li>Code is nicely modularised across multiple files. Easy to keep files small and focussed. Easy to find the code you're looking for.</li>
            <li>Everything is <a href="http://en.wikipedia.org/wiki/Don%27t_repeat_yourself">DRY</a>.</li>
            <li>No client/server mapping code. Models are bound and populated automatically in both directions.</li>
        </ul>
    </li>
</ul>
<p>Known issues:</p>
<ul>
    <li>Field-level, server-side validation failures aren't roundtripped yet (but I have an idea of how to do it)</li>
    <li>Whatever other bugs/features I didn't get to in the few short hours spent on it</li>
</ul>
<p class="testdrive-link">
    @Html.ActionLink("Testdrive POC", "Quote", "Quote")
    <a href="https://github.com/tathamoddie/KnockoutJS-Demos">View Source (Git)</a>
    <a href="http://hg.tath.am/knockoutjs-demos/src">View Source (Hg)</a>
</p>

QuotePoc.WebUI/Views/Quote/Lives.cshtml
@model QuotePoc.WebUI.Models.Life

<h3>Lives</h3>
<p>
    <button data-bind="click: addLife">Add a life</button>
</p>
<div id="quote-lives" data-bind='template: "quote-lives-template"'></div>

<script type="text/html" id="quote-lives-template">
    <table>
        <tr>
            <th>Title</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Date of Birth</th>
            <th>Age Next</th>
        </tr>
        {{each(i, life) lives()}}
            <tr>
                <td>
                    @Html.KnockoutEditorFor(l => l.Title, "value: title")
                    @Html.KnockoutValidationMessageFor(l => l.Title)
                </td>
                <td>
                    @Html.KnockoutEditorFor(l => l.FirstName, "value: firstName")
                    @Html.KnockoutValidationMessageFor(l => l.FirstName)
                </td>
                <td>
                    @Html.KnockoutEditorFor(l => l.LastName, "value: lastName")
                    @Html.KnockoutValidationMessageFor(l => l.LastName)
                </td>
                <td>
                    @Html.KnockoutEditorFor(l => l.DateOfBirth, "value: formattedDateOfBirth, valueUpdate: 'afterkeydown'")
                    @Html.KnockoutValidationMessageFor(l => l.DateOfBirth)
                </td>
                <td><span data-bind="text: ageNext" /></td>
            </tr>
        {{/each}}
    </table>
</script>

QuotePoc.WebUI/Views/Quote/Quote.cshtml
@model QuotePoc.WebUI.Models.Quote

@{
    ViewBag.Title = "Quote";
}

@section scripts {
    <script type="text/javascript" src="@Url.Content("~/Scripts/QuotePoc/life.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/QuotePoc/quote.js")"></script>
}

<h2>Quote</h2>

@Html.ValidationSummary()

@using (Html.BeginForm())
{
    <div class="quote-interface">
        @{Html.RenderPartial("Lives", new ViewDataDictionary());}
        <input type="submit" value="Calculate" data-bind="enable: submitEnabled" />
        @Html.KnockoutState()
    </div>
}

QuotePoc.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    </head>
    <body>

@RenderBody()

<script src="@Url.Content("~/Scripts/json2.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.tmpl.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/knockout-1.2.0.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/QuotePoc/site.js")" type="text/javascript"></script>
@RenderSection("scripts", false)

    </body>
</html>